### ISSUE TITLE
Generator fails, no such file or directory '.../app/css/main.css'

### ISSUE THREAD

**Issue by tinderfields** [robwierzbowski/generator-jekyllrb#11]
Installing and running generator-jekyllrb for the first time

```
fs.js:684
  return binding.stat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/Users/paulodeon/yeomantest4/app/css/main.css'
    at Object.fs.statSync (fs.js:684:18)
    at Generator.<anonymous> (/usr/local/share/npm/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/lib/actions/actions.js:97:16)
    at EventEmitter.g (events.js:175:14)
    at EventEmitter.emit (events.js:95:17)
    at /usr/local/share/npm/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/lib/util/conflicter.js:59:18
    at EventEmitter.collision (/usr/local/share/npm/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/lib/util/conflicter.js:140:12)
    at next (/usr/local/share/npm/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/lib/util/conflicter.js:54:16)
    at /usr/local/share/npm/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/lib/util/conflicter.js:60:7
    at EventEmitter.collision (/usr/local/share/npm/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/lib/util/conflicter.js:140:12)
    at next (/usr/local/share/npm/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/lib/util/conflicter.js:54:16)
```

Here are the config options selected:

```
Tell us a little about yourself. ☛
[?] Name: (Paul Odeon) 
[?] Email: (mail@paulodeon.com) 
[?] GitHub Username: (paulodeon) 
[?] Twitter Username: (@paulodeon) 

Wire tools and preprocessors. ☛
[?] Use a css preprocessor?
 s: sass
 c: compass
 n: none (n) s
[?] Use Autoprefixer? (Y/n) Y
[?] Use a javascript preprocessor?
 c: coffeescript
 n: none (n) 

Set up some directories. ☛
Nested directories are fine.
[?] Choose a css directory: (css) 
[?] Choose a javascript directory: (js) 
[?] Choose an image file directory: (image) 
[?] Choose a webfonts directory: (fonts) 
[?] Choose a css preprocessor directory: (_scss) 

Choose a template. ☛
[?] Choose a Jekyll site template
 d: default
 h5: HTML5 ★ Boilerplate (d) h5
[?] Add H5★BP css files (Y/n) y
[?] Add H5★BP javascript files? (Y/n) y
[?] Add H5★BP favorite and touch icons? (Y/n) y
[?] Add H5★BP documentation? (y/N) y
[?] Include Google Analytics? (Y/n) y

And configure Jekyll. ☛
You can change all of these options in Jekyll's _config.yml.
[?] Site Description: Site
[?] Choose a post permalink style
 d: date
 p: pretty
 n: none (d) 
[?] Markdown library
 m: maruku
 rd: rdiscount
 k: kramdown
 rc: redcarpet (m) 
[?] Use the Pygments code highlighting library? (Y/n) 
[?] Enable pagination? (Number of posts, or 'all') 
```

**Comment by aboutaaron** [comment]
Seeing this issue again with a fresh install of `0.12` and `io.js 1.2.0`; and `jekyll 1.4.3`

This with h5bp and no preprocessor

```
events.js:125
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT: no such file or directory, open '/home/aaron/.nvm/versions/io.js/v1.2.0/lib/node_modules/generator-jekyllrb/app/templates/conditional/template-h5bp/index.html'
    at Error (native)
    at Object.fs.openSync (fs.js:540:18)
    at Object.fs.readFileSync (fs.js:392:15)
    at Generator._prepCopy (/home/aaron/.nvm/versions/io.js/v1.2.0/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/lib/actions/actions.js:37:17)
    at Generator.copy (/home/aaron/.nvm/versions/io.js/v1.2.0/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/lib/actions/actions.js:70:19)
    at Generator.templates (/home/aaron/.nvm/versions/io.js/v1.2.0/lib/node_modules/generator-jekyllrb/app/index.js:457:10)
    at /home/aaron/.nvm/versions/io.js/v1.2.0/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/lib/base.js:409:16
    at processImmediate [as _immediateCallback] (timers.js:321:17)

```

With preprocessor:

```
events.js:125
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT: no such file or directory, open '/home/aaron/Code/labs/danielle/.jekyll/css/main.scss'
    at Error (native)
    at Object.fs.openSync (fs.js:540:18)
    at Object.fs.readFileSync (fs.js:392:15)
    at Generator._prepCopy (/home/aaron/.nvm/versions/io.js/v1.2.0/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/lib/actions/actions.js:37:17)
    at Generator.copy (/home/aaron/.nvm/versions/io.js/v1.2.0/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/lib/actions/actions.js:70:19)
    at Generator.templates (/home/aaron/.nvm/versions/io.js/v1.2.0/lib/node_modules/generator-jekyllrb/app/index.js:443:10)
    at /home/aaron/.nvm/versions/io.js/v1.2.0/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/lib/base.js:409:16
    at processImmediate [as _immediateCallback] (timers.js:321:17)

```

**Comment by aboutaaron** [comment]
My problem looks like it was related to having an old version of Jekyll. Upgrade to 2.5.3 seems to have solved my issues.
