### ISSUE TITLE
Installation stops with errors

### ISSUE THREAD

**Issue by sentenza** [robwierzbowski/generator-jekyllrb#114]
This issue should be connected to packages' configuration, I suppose. 

```
Using blankslate 2.1.2.4
Using chunky_png 1.3.1
Using fast-stemmer 1.0.2
Using classifier 1.3.4
Using colorator 0.1
Using highline 1.6.21
Using commander 4.1.6
Using multi_json 1.10.1
Using sass 3.4.5
Using compass-core 1.0.1
Using compass-import-once 1.0.5
Using rb-fsevent 0.9.4
Using ffi 1.9.6
Using rb-inotify 0.9.5
Using compass 1.0.1
Using liquid 2.5.5 (was 2.6.1)
Using rb-kqueue 0.2.3
Using listen 1.3.1 (was 2.7.11)
Using maruku 0.7.2
Using posix-spawn 0.3.9
Using yajl-ruby 1.1.0
Using pygments.rb 0.5.4 (was 0.6.0)
Using redcarpet 2.3.0 (was 3.2.0)
Using safe_yaml 0.9.7 (was 1.0.2)
Using parslet 1.5.0
Using toml 0.1.1
Installing jekyll 1.4.3 (was 2.4.0)
Using kramdown 1.4.2
Using bundler 1.7.3
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
/usr/local/share/gems/gems/commander-4.1.6/lib/commander/runner.rb:385:in `block in require_program': program version required (Commander::Runner::CommandError)
    from /usr/local/share/gems/gems/commander-4.1.6/lib/commander/runner.rb:384:in `each'
    from /usr/local/share/gems/gems/commander-4.1.6/lib/commander/runner.rb:384:in `require_program'
    from /usr/local/share/gems/gems/commander-4.1.6/lib/commander/runner.rb:52:in `run!'
    from /usr/local/share/gems/gems/commander-4.1.6/lib/commander/delegates.rb:8:in `run!'
    from /usr/local/share/gems/gems/commander-4.1.6/lib/commander/import.rb:10:in `block in <top (required)>'
/home/sky/.gem/ruby/gems/jekyll-1.4.3/lib/jekyll/filters.rb:2:in `require': cannot load such file -- json (LoadError)
    from /home/sky/.gem/ruby/gems/jekyll-1.4.3/lib/jekyll/filters.rb:2:in `<top (required)>'
    from /home/sky/.gem/ruby/gems/jekyll-1.4.3/lib/jekyll.rb:44:in `require'
    from /home/sky/.gem/ruby/gems/jekyll-1.4.3/lib/jekyll.rb:44:in `<top (required)>'
    from /home/sky/.gem/ruby/gems/jekyll-1.4.3/bin/jekyll:7:in `require'
    from /home/sky/.gem/ruby/gems/jekyll-1.4.3/bin/jekyll:7:in `<top (required)>'
    from /usr/local/bin/jekyll:23:in `load'
    from /usr/local/bin/jekyll:23:in `<main>'

fs.js:438
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/home/sky/workspace/materialjekyll/.jekyll/_posts/2014-10-14-welcome-to-jekyll.markdown'
    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at Generator.copy (/usr/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/lib/actions/actions.js:102:13)
    at Generator.templates (/usr/lib/node_modules/generator-jekyllrb/app/index.js:417:8)
    at /usr/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/lib/base.js:290:20
    at /usr/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/node_modules/async/lib/async.js:551:21
    at /usr/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/node_modules/async/lib/async.js:227:13
    at iterate (/usr/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/node_modules/async/lib/async.js:134:13)
    at /usr/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/node_modules/async/lib/async.js:145:25
    at /usr/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/node_modules/async/lib/async.js:229:17
```

I have already installed:
- bundler (1.7.3)
- jekyll (2.4.0, 1.5.1, 1.4.3)
- jekyll-coffeescript (1.0.1)
- jekyll-gist (1.1.0)
- jekyll-paginate (1.1.0)
- jekyll-sass-converter (1.2.1)
- jekyll-watch (1.1.1)
- json (1.8.1, 1.7.7)
- kramdown (1.4.2)

I have read that this kind of problems is related to the installation of json gem file. The version of the ruby interpreter is: `2.0.0p353 (2013-11-22 revision 43784) [i386-linux]`.
## [EDIT]

```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.2
  - RUBY VERSION: 2.0.0 (2013-11-22 patchlevel 353) [i386-linux]
  - INSTALLATION DIRECTORY: /home/sky/.gem/ruby
  - RUBY EXECUTABLE: /usr/bin/ruby
  - EXECUTABLE DIRECTORY: /home/sky/bin
  - SPEC CACHE DIRECTORY: /home/sky/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86-linux
  - GEM PATHS:
     - /home/sky/.gem/ruby
     - /usr/share/gems
     - /usr/local/share/gems
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/lib/qt-3.3/bin
     - /usr/libexec/lightdm
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/local/sbin
     - /usr/sbin
     - /opt/activator-1.2.3-minimal
     - /home/sky/.local/bin
     - /home/sky/bin
     - /opt/activator-1.2.3-minimal
```

**Comment by marfago** [comment]
Same problem.

**Comment by paulballas** [comment]
Exact same issue here

**Comment by dnozay** [comment]
node version?
based on https://travis-ci.org/dnozay/generator-jekyllrb; I can tell that it has issues with node 0.8.

**Comment by paulballas** [comment]
Node -v0.10.32

**Comment by dnozay** [comment]
npm version as well ?

**Comment by dnozay** [comment]
works with `node 0.10.35`, `npm 1.4.28` and `bundler 1.7.6`.

**Comment by gjeck** [comment]
I had the chance to try this on OSX 10.10 and Ubuntu 14.04 today. I could reproduce the error on Ubuntu but not OSX. Both systems used the following:
```bash
nvm 0.22.1
npm 2.1.18
ruby 2.2.0 
bundler 1.7.12
```
Not sure if this is helpful or not

**Comment by dnozay** [comment]
Could not repro on ubuntu 12.04 with `npm 1.4.28` but haven't tried with latest `npm`.
https://travis-ci.org/dnozay/generator-jekyllrb/jobs/46826620#L161

@gjeckl, since you are able to repro on ubuntu but not osx, it's likely an issue with your gems.
All I can think of: http://stackoverflow.com/a/22277498/1733117

**Comment by dnozay** [comment]
after #124 - the generator does not use `bundler` anymore. please check if you can repro or not.
