### ISSUE TITLE
'grunt serve' give such error.

### ISSUE THREAD

**Issue by akhalizev** [robwierzbowski/generator-jekyllrb#153]
Trying to start project but cannot start server or build app. Also I see a warning to install Jekyll. I am installing it but when I'm running 'jekyll -v' a have another error. I think there is a problem with versions but don't know how to solve it.

➜  yeo-jekyll  grunt serve
Running "serve" task

Running "clean:server" (clean) task

> > 1 path cleaned.

Running "concurrent:server" (concurrent) task

> > Warning: There are more tasks than your concurrency limit. After this limit
> > is reached no further tasks will be run until the current tasks are
> > completed. You can adjust the limit in the concurrent task options

```
Running "copy:stageCss" (copy) task
Copied 1 files

Done, without errors.


Execution Time (2015-12-11 23:06:33 UTC)
loading tasks  2.3s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 99%
copy:stageCss  33ms  ▇ 1%
Total 2.4s

Running "sass:server" (sass) task

Done, without errors.


Execution Time (2015-12-11 23:06:33 UTC)
loading tasks  2.5s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 97%
sass:server    72ms  ▇▇ 3%
Total 2.6s
    Warning: Running "jekyll:server" (jekyll) task
>> Error: Command failed: /bin/sh -c jekyll -v
>> /Users/anatolykhalizev/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/dsl.rb:34:in `instance_eval':  (Bundler::Dsl::DSLError)
>> [!] There was an error parsing `Gemfile`: syntax error, unexpected tIDENTIFIER, expecting end-of-input - gem 'jekyll', '~> 2.3.0'gem 'kramdown'gem 'sass', '~> 3.4.3'
>>                            ^. Bundler cannot continue.
>>
>>  #  from /Users/anatolykhalizev/Code/yeo-jekyll/Gemfile:3
>>  #  -------------------------------------------
>>  #
>>  >  gem 'jekyll', '~> 2.3.0'gem 'kramdown'gem 'sass', '~> 3.4.3'
>>  #  -------------------------------------------
>>  from /Users/anatolykhalizev/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/dsl.rb:34:in `eval_gemfile'
>>  from /Users/anatolykhalizev/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/dsl.rb:10:in `evaluate'
>>  from /Users/anatolykhalizev/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/definition.rb:26:in `build'
>>  from /Users/anatolykhalizev/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:155:in `definition'
>>  from /Users/anatolykhalizev/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:123:in `setup'
>>  from /Users/anatolykhalizev/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:38:in `require_from_bundler'
>>  from /Users/anatolykhalizev/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/bin/jekyll:13:in `<top (required)>'
>>  from /Users/anatolykhalizev/.rbenv/versions/2.2.3/bin/jekyll:23:in `load'
>>  from /Users/anatolykhalizev/.rbenv/versions/2.2.3/bin/jekyll:23:in `<main>'
Warning: Please install Jekyll before running this task. Use --force to continue.

Aborted due to warnings.


Execution Time (2015-12-11 23:06:37 UTC)
loading tasks  1.4s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 47%
jekyll:server  1.6s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 53%
Total 3.1s Use --force to continue.

    Aborted due to warnings.
```

Execution Time (2015-12-11 23:06:30 UTC)
loading tasks      1.7s  ▇▇▇▇▇▇▇▇▇ 18%
concurrent:server  7.7s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 81%
Total 9.4s

**Comment by scottmerker** [comment]
I have the same issue.  I think it might be version conflicts?

**Comment by YMonnier** [comment]
Same error...

```bash
 Running "jekyll:server" (jekyll) task
    >> Error: Command failed: /bin/sh -c jekyll -v
    >> WARN: Unresolved specs during Gem::Specification.reset:
    >>       jekyll-watch (~> 1.1)
    >> WARN: Clearing out unresolved specs.
    >> Please report a bug if this causes problems.
    >> /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler/runtime.rb:40:in `block in setup': You have already activated colorator 1.1.0, but your Gemfile requires colorator 0.1. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
    >> 	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler/runtime.rb:25:in `map'
    >> 	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler/runtime.rb:25:in `setup'
    >> 	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler.rb:99:in `setup'
    >> 	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.3.1/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
    >> 	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.3.1/exe/jekyll:9:in `<top (required)>'
    >> 	from /usr/local/bin/jekyll:22:in `load'
    >> 	from /usr/local/bin/jekyll:22:in `<main>'
    Warning: Please install Jekyll before running this task. Used --force, continuing.
    Warning: Task "jekyll:server" failed. Used --force, continuing.
```

**Comment by YMonnier** [comment]
I solved my problem by updating Jekyll.

Regards
