### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by YewTreeWeb** [robwierzbowski/generator-jekyllrb#160]
Hi,

Every time I select number of pages option I get the error:

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/Mat/Documents/Sites/Git/yeoman-website/yeoman-jekyll/.jekyll/_layouts/post.html'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Generator._prepCopy (/usr/local/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/lib/actions/actions.js:37:17)
    at Generator.copy (/usr/local/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/lib/actions/actions.js:70:19)
    at Generator.templates (/usr/local/lib/node_modules/generator-jekyllrb/app/index.js:442:10)
    at /usr/local/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/lib/base.js:409:16
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback](timers.js:529:5)

Am I doing something wrong? Any help would be much appreciated. I have yeoman 1.8.4 and have just download jekyllrb. 

Thank you for taking the time to read my email. I look forward to your reply.

**Comment by jurepolutnik** [comment]
+1

**Comment by YewTreeWeb** [comment]
Hi @jurepolutnik I have managed to resolve this error. What I did was find where my npm is located (default /usr/local/) then run the command 'sudo chown -R user_name /usr/local/' 

I hope this helps you. However I have since run into another problem when I try to run grunt serve, where it says 'Fatal error: Unable to find local grunt.' 

I can fix this by doing npm install,  but then I get an error from grunt saying 'jekyll needs to be installed'
