### ISSUE TITLE
Jekyll command runs before bundle install

### ISSUE THREAD

**Issue by dcalhoun** [robwierzbowski/generator-jekyllrb#54]
The jekyllrb generator has worked for me in the past, but now when running `yo jekyllrb` for a fresh project I'm getting the error below. Is it possibly related to [this change](https://github.com/robwierzbowski/generator-jekyllrb/issues/17#issuecomment-29540258) and that [bundle exec jekyll](https://github.com/robwierzbowski/generator-jekyllrb/blob/master/app/index.js#L371) is running before [bundle install](https://github.com/robwierzbowski/generator-jekyllrb/blob/master/app/index.js#L41)?

``` bash
[...]
[?] Number of posts to show on the home page: all
   create .gitignore
   create .gitattributes
   create Gruntfile.js
   create package.json
   create .bowerrc
   create bower.json
   create Gemfile
   create .jshintrc
   create .csslintrc
   create .editorconfig
bundler: command not found: jekyll
Install missing gem executables with `bundle install`

fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/Users/username/Sites/other/jekyll-test/.jekyll/_posts/2013-12-19-welcome-to-jekyll.markdown'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at Generator.copy (/usr/local/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/lib/actions/actions.js:102:13)
    at Generator.templates (/usr/local/lib/node_modules/generator-jekyllrb/app/index.js:394:8)
    at /usr/local/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/lib/base.js:290:20
    at /usr/local/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/node_modules/async/lib/async.js:548:21
    at /usr/local/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/node_modules/async/lib/async.js:224:13
    at iterate (/usr/local/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/node_modules/async/lib/async.js:131:13)
    at /usr/local/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/node_modules/async/lib/async.js:142:25
    at /usr/local/lib/node_modules/generator-jekyllrb/node_modules/yeoman-generator/node_modules/async/lib/async.js:226:17
```

**Comment by utkjad** [comment]
I am still facing the issue with current version of jekyll. Is there any workaround for this?
